apiVersion: v1
kind: Pod
metadata:
  name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op0-{{ .Values.operator.op0.device.hostname }}
spec:
  #restartPolicy: Never
  containers:
  - name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op0-{{ .Values.operator.op0.device.hostname }}
    image: yclo/tensorflow-yolo-opencv:fifth
    resources:
      requests:
        memory: "{{ .Values.operator.op0.resource.mem }}M"
        cpu: "{{ .Values.operator.op0.resource.cpu }}m"
    ports:
    - containerPort: {{ .Values.operator.op0.port }}
      hostPort: {{ .Values.operator.op0.port }}
    command: ["/bin/bash","-c","python3 worker.py --worker_hosts={{ .Values.operator.op0.ip }}:{{ .Values.operator.op0.port }},{{ .Values.operator.op1.ip }}:{{ .Values.operator.op1.port }},{{ .Values.operator.op2.ip }}:{{ .Values.operator.op2.port }} --job_name=worker --task_index=0"]
    securityContext:
      privileged: true
    env:
    - name : MASTER_IP
      value: {{ .Values.operator.op0.ip }}
    - name : MASTER_PORT
      value: "{{ .Values.operator.op0.port }}"
    - name : BROKER
      value: {{ .Values.mqtt.brokerIP }}
    - name : PERIOD
      value: "{{ .Values.period }}"
    - name : REQUEST
      value: "{{ .Values.name.request }}"
    # no ps worker in tensorflow, so the value start from 1
    - name : OP0
      value: "1"
    - name : OP1
      value: "2"
  nodeSelector:
    device: "{{ .Values.operator.op0.device.label }}"
